#####################################################
################# Spring properties #################
#####################################################
spring:
  application:
    name: core-service-nft
  datasource:
    url: jdbc:postgresql://localhost:5432/core-service-nft
    username: root
    password: root
    hikari:
      minimumIdle: 2
      idleTimeout: 120000
      maxLifetime: 900000
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
#  liquibase:
#    enabled: true
#    change-log: classpath:db/liquibase-changelog.xml
#####################################################
################# Server properties #################
#####################################################
server:
  port: 9087
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  shutdown: graceful